### ISSUE TITLE
Support sub-samples

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/drupal-7-module-indicia-api#10]
Samples within samples.

**Comment by johnvanbreda** [comment]
Just in case you aren't aware, subsamples are supported in the data model and in the submission format, so it is just a case of supporting this in the API.

**Comment by kazlauskis** [comment]
Yep, thanks John, is there any other record structure I should be aware of? I am basically trying to replicate warehouse models on the client (morel).

**Comment by johnvanbreda** [comment]
Have you seen https://github.com/Indicia-Team/drupal-7-module-iform/blob/master/modules/iform_ajaxproxy/iform_ajaxproxy.module#125 - this code is the ajax proxy which accepts form posts from clients and covers the structures we've needed to post via this method.
